spring.application.name=Xpay


#Connection port
server.port = 8096

# APPLICATION PROPERTIES FOR DATABASE
# DATABASE ===============================================================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/Xpay
spring.datasource.username=user_data
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# Prevent Hibernate from creating Enum CHECK constraints from Bean Validation annotations
spring.jpa.properties.hibernate.validator.apply_to_ddl=false


# Controls the schema generation strategy: create, create-drop, update, validate, none
spring.jpa.properties.hibernate.hbm2ddl.auto=update


# HikariCP Configuration For Large User Base With Many Concurrent Database Requests.
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=50
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.pool-name=xpay-HikariPool

# HIBERNATE - SQL =======================================================================================================

# Servlet port
server.servlet.context-path=/api



