spring.application.name=Xpay

# Connection port
server.port=8080
server.servlet.context-path=/api

# ==========================================
# Azure SQL Database Configuration (Xpay)
# ==========================================

# 1. Connection URL
spring.datasource.url=jdbc:sqlserver://xpay-db.database.windows.net:1433;database=xpay-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# 2. Database Authentication (Secured via Environment Variables)
spring.datasource.username=${AZURE_DB_USER:xpay-db}
spring.datasource.password=${AZURE_DB_PASSWORD:Fumbi442$}

# 3. Microsoft SQL Server Driver Class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Hibernate / JPA Settings Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update

# HikariCP Configuration For Large User Base With Many Concurrent Database Requests.
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=50
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.pool-name=xpay-HikariPool

# EMAIL NOTIFICATION ====================================================================================================

# Set this to true after SMTP credentials are configured.
xpay.notification.email.enabled=true
xpay.notification.email.from=no-reply@xpay.local

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
